server:
  port: 9001

spring:
  application:
    name: nacos-privider-payment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #配置nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'