server:
  port: 2001
spring:
  application:
    name: seata-order-servcie
  cloud:
#    alibaba:
#      seata:
        #自定义事务组名需要与seata-server中的对应
        #默认就是为defult，这个可以自己定义，在seata1.0之前，/conf/file.conf中的service中可以定义
#        tx-service-group: cn_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
