server:
  port: 83
spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos主机名和端口号

#消费者将要去访问的微服务的地址名称，不用再到controller中定义baseURL，配置与代码分离
service-url:
  nacos-user-service: http://nacos-privider-payment